### ISSUE TITLE
apply_spikes() Spike Time Values Are Absolute Not Relative

### ISSUE THREAD

**Issue by BGull00** [TENNLab-UTK/fpga#40]
The TENNLab framework RISP simulator works such that the time value for each Spike in an `apply_spikes()` call is relative to the current timestep instead of an absolute global timestep value. In other words, you can schedule an input spike for the upcoming timestep by calling `apply_spikes()` with a Spike with a time value of 0 at any time, even after calling `run()`. Here is an example of a valid processor tool command sequence:
AS 0 0 1
RUN 1
AS 0 0 1
RUN 1

Currently, the code in `_processor.py` does not support this and returns the following error: `Spikes cannot be scheduled in the past.`

**Comment by keegandent** [comment]
@BGull00 So to be clear, the times in `output_vector`, `output_count`, and `output_last_fire` along with their plural counterparts should _all_ only return data based on output spikes since the timestamp of the most recent `run` call _and relative to that timestamp_? So Basically there should never be a timestamp outside $$[0, N-1]$$ for a `run(N)` call?

**Comment by BGull00** [comment]
@keegandent Yes what you said is exactly correct. There should never be a timestep outside [0,N-1] for a `run(N)` call.
